### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by panagiotis1962** [y368413/2-UI#2]
My issue is you have gone all quiet.
I hope all is well and you are still working on this beautiful UI.
If you can let us know either way will be appreciated.
If you are great can't wait as someone created a copy of your UI and is passing it on as an update lol.
If you are not going to be playing or working on it anymore I just like to take the time and thank you for all these years and good luck whatever the future holds for you.
Thanks, Meggalo wowinterface.

我的問題是你已經完全安靜了。
我希望一切都好，並且您仍在開發這個漂亮的 UI。
如果您能讓我們知道任何一種方式，我們將不勝感激。
如果你很棒，等不及有人創建了你的 UI 副本並將其作為更新傳遞，哈哈。
如果你不再參加比賽或繼續努力，我只想花時間感謝你這些年，無論你的未來如何，祝你好運。

**Comment by y368413** [comment]
updata
